version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306  
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: quizy
      MYSQL_USER: naoki
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret 

      


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=naoki
      - PMA_PASSWORD=password
    depends_on:
      - db